name: "GET IP Iran"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  runscript:
    name: GetIP
    runs-on: ubuntu-latest
    
    # ۱. افزودن دسترسی نوشتن به ریپازیتوری برای این جاب
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        # ۲. استفاده از نسخه مشخص برای پایداری بیشتر
        uses: actions/checkout@v4

      - name: ایجاد لیست، کامیت و پوش کردن تغییرات
        run: |
          bash get.sh > list.rsc
          git config --global user.email "elyasmankan@users.noreply.github.com"
          git config --global user.name "elyasmankan"
          git add list.rsc
          # فقط در صورتی که تغییری وجود داشته باشد، کامیت انجام می‌شود
          if ! git diff-index --quiet HEAD; then
            git commit -m "Automatic update"
            git push
          fi
